const state={data:null,series:null,health:null,selected:null,period:'1M',page:'home',filter:'ALL',query:'',favs:new Set(JSON.parse(localStorage.getItem('alpha-v9-favs')||'[]')),chartPoints:[]};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const pct=(v,d=2)=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${num(v,d)}%`:'—';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function price(v,c=''){if(!Number.isFinite(Number(v)))return'—';const n=Number(v);if(c==='EUR')return n.toLocaleString('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:n<10?3:2});if(c==='USD')return n.toLocaleString('it-IT',{style:'currency',currency:'USD',maximumFractionDigits:n<10?3:2});if(c==='%')return `${num(n,3)}%`;return num(n,n<10?3:2)}
function age(ts){if(!ts)return'—';const m=(Date.now()-new Date(ts).getTime())/60000;if(m<1)return'<1 min';if(m<60)return`${Math.round(m)} min`;return`${Math.round(m/60)} h`}
function allAssets(){const map=new Map();for(const x of [...(state.data?.signals||[]),...(state.data?.watchlist||[])])if(x?.ticker&&!map.has(x.ticker))map.set(x.ticker,x);return map}
function asset(t){return allAssets().get(t)||null}
function seriesMeta(t){return state.series?.symbols?.[t]||null}
function points(t,period=state.period){const s=seriesMeta(t);if(!s)return[];let p=[];if(period==='1D'&&Array.isArray(s.intraday)&&s.intraday.length){const last=s.intraday[s.intraday.length-1]?.[0]?.slice(0,10);p=s.intraday.filter(x=>String(x[0]).slice(0,10)===last)}else{const d=Array.isArray(s.daily)?s.daily:[];const n={ '1W':6,'1M':23,'3M':66,'1Y':270}[period]||23;p=d.slice(-n)}return p.filter(x=>Array.isArray(x)&&x.length===2&&Number.isFinite(Number(x[1])))}
function changeFor(t,period=state.period){const p=points(t,period);if(p.length<2)return null;const a=Number(p[0][1]),b=Number(p[p.length-1][1]);return a?((b/a)-1)*100:null}
function lastPrice(t){const p=points(t,'1D');if(p.length)return Number(p[p.length-1][1]);const s=seriesMeta(t);if(s?.daily?.length)return Number(s.daily[s.daily.length-1][1]);const a=asset(t);return Number(a?.quote_price??a?.entry_price??a?.price)}
function displayName(t){return asset(t)?.display_ticker||asset(t)?.name||seriesMeta(t)?.display||t}
function currency(t){return asset(t)?.currency||seriesMeta(t)?.currency||''}
function sparkPath(vals,w=220,h=44,pad=2){if(vals.length<2)return'';const ys=vals.map(x=>Number(x[1]));const lo=Math.min(...ys),hi=Math.max(...ys),span=hi-lo||1;return vals.map((x,i)=>`${i?'L':'M'}${pad+(i/(vals.length-1))*(w-pad*2)},${pad+(1-(Number(x[1])-lo)/span)*(h-pad*2)}`).join(' ')}
function spark(t){const p=points(t,'1M');if(p.length<2)return'<div class="meta">Grafico non disponibile</div>';const c=changeFor(t,'1M');return`<svg viewBox="0 0 220 44" preserveAspectRatio="none" class="${c>=0?'positive':'negative'}"><path class="miniLine" d="${sparkPath(p)}"/></svg>`}
function setPeriod(p){state.period=p;document.querySelectorAll('.period').forEach(b=>b.classList.toggle('active',b.dataset.period===p));renderHero()}
function selectTicker(t){state.selected=t;showPage('home');renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function toggleFav(ev,t){ev.stopPropagation();state.favs.has(t)?state.favs.delete(t):state.favs.add(t);localStorage.setItem('alpha-v9-favs',JSON.stringify([...state.favs]));renderWatch()}
function showPage(p){state.page=p;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${p}`));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.page===p))}
function chartSvg(p){if(p.length<2)return'';const w=1000,h=250,pad=8;const ys=p.map(x=>Number(x[1]));const lo=Math.min(...ys),hi=Math.max(...ys),span=hi-lo||1;const path=p.map((x,i)=>`${i?'L':'M'}${pad+(i/(p.length-1))*(w-pad*2)},${pad+(1-(Number(x[1])-lo)/span)*(h-pad*2)}`).join(' ');const area=`${path} L ${w-pad},${h-pad} L ${pad},${h-pad} Z`;return`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line class="chartGrid" x1="0" y1="${h*.25}" x2="${w}" y2="${h*.25}"/><line class="chartGrid" x1="0" y1="${h*.5}" x2="${w}" y2="${h*.5}"/><line class="chartGrid" x1="0" y1="${h*.75}" x2="${w}" y2="${h*.75}"/><path class="chartFill" d="${area}"/><path class="chartLine" d="${path}"/></svg>`}
function renderHero(){if(!state.data)return;const t=state.selected;const a=asset(t);const m=seriesMeta(t);const p=points(t);state.chartPoints=p;const ch=changeFor(t);const lp=lastPrice(t);$('heroEyebrow').textContent=`${a?.asset_class||m?.asset_class||'MARKET'} · ${a?.cluster||'OBSERVED SERIES'}`;$('heroName').textContent=displayName(t);$('heroPrice').textContent=price(lp,currency(t));$('heroChange').textContent=ch==null?'Performance periodo non disponibile':`${pct(ch)} · ${state.period}`;$('heroChange').className=`change ${ch==null?'neutral':ch>=0?'positive':'negative'}`;const badge=$('heroSignal');badge.textContent=a?.direction?`${a.direction} · SCORE ${num(a.score,0)}`:'MARKET';badge.className=`signalBadge ${(a?.direction||'').toLowerCase()}`;const shell=$('chartShell');shell.className=`chartShell ${ch==null?'flat':ch>=0?'up':'down'}`;$('mainChart').innerHTML=p.length>=2?chartSvg(p):'<div class="chartEmpty">Serie osservata non disponibile per questo periodo</div>';const stats=[['Confidence',a?.confidence_pct!=null?`${num(a.confidence_pct,1)}%`:'—'],['Horizon',a?.horizon?`${a.horizon} sedute`:'—'],['Risk',a?.risk_level||'—'],['RSI 14',a?.rsi!=null?num(a.rsi,1):'—'],['Vol 20',a?.volatility_pct!=null?`${num(a.volatility_pct,2)}%`:'—'],['Data quality',a?.data_quality_score!=null?`${num(a.data_quality_score,0)}/100`:'—']];$('heroStats').innerHTML=stats.map(x=>`<div class="stat"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('');bindChartPointer()}
function bindChartPointer(){const box=$('chartShell'),tip=$('chartTip');box.onpointermove=e=>{const p=state.chartPoints;if(p.length<2)return;const r=box.getBoundingClientRect();const idx=clamp(Math.round(((e.clientX-r.left)/r.width)*(p.length-1)),0,p.length-1);const x=clamp(e.clientX-r.left,26,r.width-26);const row=p[idx];tip.style.display='block';tip.style.left=`${x}px`;tip.style.top=`${Math.max(24,e.clientY-r.top)}px`;const dt=new Date(row[0]);tip.textContent=`${dt.toLocaleString('it-IT',{day:'2-digit',month:'short',hour:state.period==='1D'?'2-digit':undefined,minute:state.period==='1D'?'2-digit':undefined})} · ${price(row[1],currency(state.selected))}`};box.onpointerleave=()=>tip.style.display='none'}
const macroSymbols=['SPY','QQQ','^VIX','^TNX','EURUSD=X','GC=F','CL=F','BTC-USD'];
function renderTape(){$('tape').innerHTML=macroSymbols.map(t=>{const p=lastPrice(t),c=changeFor(t,'1D');return`<button class="tapeCard" onclick="selectTicker('${esc(t)}')"><b>${esc(seriesMeta(t)?.display||t)}</b><span>${esc(price(p,currency(t)))}</span><em class="${c==null?'neutral':c>=0?'positive':'negative'}">${esc(c==null?'—':pct(c))}</em></button>`}).join('')}
function renderSummary(){const d=state.data,m=d.market||{},q=d.data_quality||{},mem=d.memory||{},div=d.diversification||{};const cards=[['Market regime',m.risk_regime||'—',`${m.rates_regime||'—'} · ${m.italy_bond_regime||'—'}`],['Coverage',`${num((q.availability_ratio||0)*100,1)}%`,`${q.quote_count||0} quote · ${q.universe_count||0} strumenti`],['Diversification',num(div.score,1),`${div.asset_classes||0} asset class · HHI ${num(div.hhi,2)}`],['Track record',mem.resolved||0,mem.resolved?`Hit rate ${pct((mem.hit_rate||0)*100,1)}`:'Previsioni non ancora mature']];$('summaryGrid').innerHTML=cards.map(c=>`<div class="card"><div class="k">${esc(c[0])}</div><div class="v">${esc(c[1])}</div><div class="n">${esc(c[2])}</div></div>`).join('')}
function renderIdeas(){const list=(state.data.signals||[]).slice(0,4);$('ideas').innerHTML=list.map(a=>{const ch=changeFor(a.ticker,'1M');return`<article class="idea" onclick="selectTicker('${esc(a.ticker)}')"><div class="ideaHead"><div><div class="ticker">${esc(a.display_ticker||a.ticker)}</div><div class="meta">${esc(a.asset_class)} · ${esc(a.cluster)}</div></div><div><div class="ideaScore">${num(a.score,0)}</div><div class="sigDir ${a.direction==='LONG'?'positive':'negative'}">${esc(a.direction)}</div></div></div><div class="spark ${ch==null?'neutral':ch>=0?'positive':'negative'}">${spark(a.ticker)}</div><div class="ideaFoot"><div class="miniStat"><span>CONF.</span><b>${num(a.confidence_pct,1)}%</b></div><div class="miniStat"><span>HORIZON</span><b>${a.horizon||'—'}d</b></div><div class="miniStat"><span>R/R T1</span><b>${a.risk_reward_1?num(a.risk_reward_1,1):'—'}</b></div></div></article>`}).join('')||'<div class="errorBox">Nessun segnale validato disponibile.</div>'}
function watchRows(){const map=allAssets();return [...map.values()].sort((a,b)=>(state.favs.has(b.ticker)-state.favs.has(a.ticker))||(b.score||0)-(a.score||0)).filter(a=>!state.query||`${a.ticker} ${a.name||''} ${a.asset_class||''}`.toLowerCase().includes(state.query.toLowerCase())).slice(0,50)}
function renderWatch(){const list=watchRows();$('watchList').innerHTML=list.map(a=>{const ch=changeFor(a.ticker,'1M');return`<div class="watchRow" onclick="selectTicker('${esc(a.ticker)}')"><button class="fav ${state.favs.has(a.ticker)?'on':''}" onclick="toggleFav(event,'${esc(a.ticker)}')">★</button><div class="watchName"><b>${esc(a.display_ticker||a.ticker)}</b><span>${esc(a.asset_class)} · score ${num(a.score,0)}</span></div><div class="watchPrice">${esc(price(lastPrice(a.ticker),a.currency))}</div><div class="watchChange ${ch==null?'neutral':ch>=0?'positive':'negative'}">${esc(ch==null?'—':pct(ch))}</div><div class="sigDir ${a.direction==='LONG'?'positive':'negative'}">${esc(a.direction||'—')}</div></div>`}).join('')||'<div class="errorBox">Nessuno strumento trovato.</div>'}
function setFilter(f){state.filter=f;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===f));renderSignals()}
function renderFilters(){const classes=[...new Set((state.data.signals||[]).map(x=>x.asset_class).filter(Boolean))];$('filters').innerHTML=['ALL',...classes].map(f=>`<button class="filter ${f==='ALL'?'active':''}" data-filter="${esc(f)}" onclick="setFilter('${esc(f)}')">${esc(f==='ALL'?'TUTTI':f.replaceAll('_',' '))}</button>`).join('')}
function renderSignals(){let list=state.data.signals||[];if(state.filter!=='ALL')list=list.filter(x=>x.asset_class===state.filter);$('signals').innerHTML=list.map(a=>`<article class="signalCard" onclick="selectTicker('${esc(a.ticker)}')"><div class="sigTop"><div><div class="ticker">${esc(a.display_ticker||a.ticker)}</div><div class="meta">${esc(a.asset_class)} · ${esc(a.cluster)} · ${esc(a.role||'')}</div></div><div><div class="sigScore">${num(a.score,0)}</div><div class="sigDir ${a.direction==='LONG'?'positive':'negative'}">${esc(a.direction)}</div></div></div><div class="sigGrid"><div class="sigCell"><span>ENTRY</span><b>${esc(price(a.entry_price,a.currency))}</b></div><div class="sigCell"><span>STOP</span><b>${esc(price(a.stop_price,a.currency))}</b></div><div class="sigCell"><span>TARGET 1</span><b>${esc(price(a.target1_price,a.currency))}</b></div><div class="sigCell"><span>TARGET 2</span><b>${esc(price(a.target2_price,a.currency))}</b></div><div class="sigCell"><span>CONFIDENCE</span><b>${num(a.confidence_pct,1)}%</b></div><div class="sigCell"><span>HORIZON</span><b>${a.horizon||'—'} sedute</b></div><div class="sigCell"><span>RSI</span><b>${num(a.rsi,1)}</b></div><div class="sigCell"><span>VOL</span><b>${a.volatility_pct!=null?`${num(a.volatility_pct,2)}%`:'—'}</b></div></div><div class="reason">${esc((a.reasons||[]).slice(0,3).join(' · '))}</div></article>`).join('')||'<div class="errorBox">Nessun segnale per questo filtro.</div>'}
function renderMacro(){const m=state.data.market||{};const cards=[['VIX',m.vix,'Risk temperature'],['S&P 500 20D',m.spy_20d_pct!=null?`${pct(m.spy_20d_pct)}`:'—',m.risk_regime],['US 10Y',m.us10y_yield_pct!=null?`${num(m.us10y_yield_pct,3)}%`:'—',`${num(m.us10y_change_20d_bps,1)} bps / 20D`],['DXY',m.dxy,'Dollar index'],['Gold 20D',m.gold_20d_pct!=null?pct(m.gold_20d_pct):'—','Commodity momentum'],['Oil 20D',m.oil_20d_pct!=null?pct(m.oil_20d_pct):'—','Energy momentum'],['EUR/USD',m.eurusd,'FX'],['Italy Gov 20D',m.italy_gov_bond_20d_pct!=null?pct(m.italy_gov_bond_20d_pct):'—',m.italy_bond_regime]];$('macroGrid').innerHTML=cards.map(c=>`<div class="macroCard"><span>${esc(c[0])}</span><b>${esc(c[1]??'—')}</b><em>${esc(c[2]??'')}</em></div>`).join('')}
function renderLab(){const d=state.data,a=asset(state.selected)||d.signals?.[0]||{},mem=d.memory||{},q=d.data_quality||{},bt=d.backtest||{},ext=d.external_models||{},cost=d.execution_assumptions?.cost_bps_by_asset_class||{};$('labGrid').innerHTML=`<div class="card"><div class="k">DATA HEALTH</div><div class="v">${num((q.availability_ratio||0)*100,1)}%</div><div class="rows"><div class="dataRow"><span>Universe</span><b>${q.universe_count||0}</b></div><div class="dataRow"><span>Quote overlay</span><b>${q.quote_count||0}</b></div><div class="dataRow"><span>Missing</span><b>${(q.unavailable_tickers||[]).length}</b></div><div class="dataRow"><span>Chart feed</span><b>${esc(state.series?.status||'—')} ${state.series?.available_symbols||0}/${state.series?.requested_symbols||0}</b></div></div></div><div class="card"><div class="k">MODEL GOVERNANCE</div><div class="v">V8.5</div><div class="rows"><div class="dataRow"><span>Edge Core</span><b>${esc(d.edge_core?.version||'—')}</b></div><div class="dataRow"><span>No look-ahead</span><b>${d.model_learning?.no_lookahead?'ON':'OFF'}</b></div><div class="dataRow"><span>Resolved</span><b>${mem.resolved||0}</b></div><div class="dataRow"><span>Backtest</span><b class="${bt.state==='OK'?'positive':'negative'}">${esc(bt.state||'—')}</b></div></div></div><div class="card"><div class="k">EXTERNAL CONSENSUS</div><div class="v">${ext.tracked_models||0}</div><div class="n">Modelli esterni tracciati. Nessun boost positivo finché il track record non è maturo.</div><div class="rows"><div class="dataRow"><span>Accepted</span><b>${ext.accepted||0}</b></div><div class="dataRow"><span>Positive boost</span><b>${ext.positive_boost_enabled?'ON':'OFF'}</b></div></div></div><div class="card labWide"><div class="k">${esc(a.display_ticker||a.ticker||'SELECTED')} · MODEL VOTES</div><div class="rows">${(a.model_votes||[]).map(v=>`<div class="vote"><div class="voteHead"><span>${esc(v.model_id)} · ${esc(v.direction)}</span><b>${num(v.score,0)}</b></div><div class="bar"><i style="width:${clamp(Number(v.score)||0,0,100)}%"></i></div></div>`).join('')||'<div class="n">Nessun voto disponibile.</div>'}</div></div><div class="card"><div class="k">ROUND-TRIP COST MODEL</div><div class="rows">${Object.entries(cost).slice(0,10).map(([k,v])=>`<div class="dataRow"><span>${esc(k.replaceAll('_',' '))}</span><b>${num(v,0)} bps</b></div>`).join('')}</div></div>`}
function renderStatus(){const ts=state.data?.engine_updated_at||state.data?.updated_at;const mins=(Date.now()-new Date(ts).getTime())/60000;const dot=$('liveDot');dot.className=`dot ${mins>90?'bad':mins>35?'warn':''}`;$('liveText').textContent=`LIVE · ${age(ts)}`;$('updatedLabel').textContent=`Engine ${age(ts)} · market ${age(state.data?.market_data_at)}`}
function renderAll(){renderStatus();renderHero();renderTape();renderSummary();renderIdeas();renderWatch();renderSignals();renderMacro();renderLab()}
async function load(){try{const [d,s,h]=await Promise.allSettled([fetch('data/latest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('latest');return r.json()}),fetch('data/market-series.json',{cache:'no-store'}).then(r=>r.ok?r.json():null),fetch('data/automation-health.json',{cache:'no-store'}).then(r=>r.ok?r.json():null)]);if(d.status!=='fulfilled')throw Error('Dati Alpha non disponibili');state.data=d.value;state.series=s.status==='fulfilled'?s.value:null;state.health=h.status==='fulfilled'?h.value:null;const first=(state.data.signals||[]).find(x=>seriesMeta(x.ticker))?.ticker||(state.data.signals||[])[0]?.ticker||(state.series&&Object.keys(state.series.symbols||{})[0])||'SPY';state.selected=first;renderFilters();renderAll();$('loading').style.display='none';$('content').style.display='block'}catch(e){$('loading').innerHTML=`<div class="errorBox">Alpha non riesce a caricare il feed: ${esc(e.message)}. Il sistema non inventa dati in fallback.</div>`}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.period').forEach(b=>b.addEventListener('click',()=>setPeriod(b.dataset.period)));document.querySelectorAll('.bottom button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));$('search').addEventListener('input',e=>{state.query=e.target.value;renderWatch()});load();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
