(()=>{
'use strict';
const fmt=ts=>{if(!ts)return'—';try{return new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Rome'}).format(new Date(ts))}catch{return String(ts)}};
const ageMin=ts=>{const n=ts?new Date(ts).getTime():NaN;return Number.isFinite(n)?Math.max(0,(Date.now()-n)/60000):Infinity};
function romeClock(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Rome',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()),v=Object.fromEntries(p.map(x=>[x.type,x.value]));return{weekday:v.weekday,minutes:Number(v.hour)*60+Number(v.minute)}}
function marketContext(){const c=romeClock();if(['Sat','Sun'].includes(c.weekday))return{open:false,label:'MERCATO CHIUSO'};const open=c.minutes>=540&&c.minutes<=1080;return{open,label:open?'MERCATO APERTO':'MERCATO CHIUSO'}}
async function getData(){try{const r=await fetch('data/latest.json?ux='+Date.now(),{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
function ensureBanner(){let box=document.getElementById('alphaNicheStatus');if(box)return box;const host=document.querySelector('.topbar');if(!host)return null;box=document.createElement('div');box.id='alphaNicheStatus';box.className='notice';box.style.margin='0 0 12px';host.insertAdjacentElement('afterend',box);return box}
function apply(d){const ctx=marketContext(),ts=d?.market_data_at||d?.updated_at,mins=ageMin(ts),box=ensureBanner(),liveText=document.getElementById('liveText'),dot=document.getElementById('liveDot'),updated=document.getElementById('updatedLabel');if(!box)return;
 if(!ctx.open){box.style.borderColor='rgba(63,211,148,.35)';box.innerHTML=`<b>MERCATO CHIUSO</b> · Prezzi fermi all’ultima osservazione ufficiale: non è un errore di aggiornamento. Ultimo dato reale: ${fmt(ts)}. Il live riprende alla riapertura.`;if(liveText)liveText.textContent=`MERCATO CHIUSO · ${Number.isFinite(mins)?Math.round(mins/60)+' h':'—'}`;if(dot)dot.className='dot';if(updated)updated.textContent=`Ultimo prezzo reale ${fmt(ts)} · mercato chiuso`;return}
 const delayed=!Number.isFinite(mins)||mins>45;box.style.borderColor=delayed?'rgba(255,107,107,.35)':'rgba(90,167,255,.35)';box.innerHTML=delayed?`<b>DATI IN RITARDO</b> · Il mercato è aperto ma l’ultimo prezzo reale è del ${fmt(ts)}. Il dato viene segnalato come non fresco, senza inventare aggiornamenti.`:`<b>MERCATO APERTO</b> · Prezzi in sessione. Ultimo dato reale: ${fmt(ts)}.`;if(liveText)liveText.textContent=delayed?'DATI IN RITARDO':'MERCATO APERTO';if(dot)dot.className=`dot ${delayed?'bad':''}`;if(updated)updated.textContent=`Ultimo prezzo reale ${fmt(ts)} · ${delayed?'ritardo da verificare':'sessione attiva'}`}
async function run(){apply(await getData())}
function start(){run();setInterval(()=>{if(!document.hidden)run()},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)run()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();